[package]
name = "quantion"
version = "0.1.2"
edition = "2024"

[lib]
name = "quantion"
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "unwind"
debug = false
strip = "symbols"

[dependencies]
bytes = "1.12.1"
ionic-rs = "0.1.2"
memmap2 = "0.9.11"
serde = { version = "1.0.229", features = ["derive", "rc"] }

[target.'cfg(not(all(target_arch = "wasm32", not(target_os = "wasi"))))'.dependencies]
rayon = "1.12.0"

[build-dependencies]
cbindgen = "0.29.4"
